# fly.toml app configuration file generated for uog-webdev-2024 on 2024-01-15T14:40:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uog-webdev-2024"
primary_region = "ams"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "uog-webdev-2024.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
